version: '2'
services:
  develop:
    image: guizar/data-sci-notebooks:latest
    build: .
    container_name: helixscope-datasci-notebook
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
